### ISSUE TITLE
givevehicle

### ISSUE THREAD

**Issue by ritchehostsailor** [JGCdev/xex_rewards#2]
script:es_extended] [WARNING] Server callback "esx_vehicleshop:giveVehicle" does not exist. Please Check The Server File for Errors!

**Comment by ritchehostsailor** [comment]
no fix yet?

**Comment by JGCdev** [comment]
esx_vehicleshop is a dependency, please read readme.md file and forum post.

Not a issue.

**Comment by ritchehostsailor** [comment]
I know I have esx_vehicleshop but that is the error when getting the car. However, the cash gift is working fine.
